name: basics
on: [push, pull_request]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t solana-eval .
      - name: Run hello-world tests
        run: docker run --rm -v ${{ github.workspace }}:/workspace solana-eval \
               ./scripts/test_example.sh basics/hello-world
